### ISSUE TITLE
Ignore when a non-command string typed in chat

### ISSUE THREAD

**Issue by arvryna** [requiemofthesouls/pigeomail#17]
**Describe the bug**
when you type something that is not a command, a message is shown as "Internal error, please try again later..."

**Expected behavior**
Hide that message

**Screenshots**
![image](https://user-images.githubusercontent.com/4346153/150166553-af11146c-72bb-46a4-888f-0a58f7757611.png)

**Comment by arvryna** [comment]
Fix: is it okay to just remove the line 21 ? or should it be handled in a different way ?

![image](https://user-images.githubusercontent.com/4346153/150166802-3572982f-05c2-461f-9dc2-a6c488712883.png)

**Comment by arvryna** [comment]
okay, i will create a sentry account and send logs there. Each and every logs must go there ?

**Comment by requiemofthesouls** [comment]
> okay, i will create a sentry account and send logs there. Each and every logs must go there ?

add sentry in docker compose and send only errors there

**Comment by arvryna** [comment]
need a clarification = " add sentry in docker compose"  .. you mean to add the [self-hosted](https://develop.sentry.dev/self-hosted/) version of sentry service running in our server OR you just want to use only the api-key, install sentry go-sdk and get started ?

**Comment by requiemofthesouls** [comment]
> need a clarification = " add sentry in docker compose"  .. you mean to add the [self-hosted](https://develop.sentry.dev/self-hosted/) version of sentry service running in our server OR you just want to use only the api-key, install sentry go-sdk and get started ?

we can start from SaaS version, self-hosted will be installed if free plan will be expired

**Comment by requiemofthesouls** [comment]
> > okay, i will create a sentry account and send logs there. Each and every logs must go there ?
> 
> add sentry in docker compose and send only errors there

just realized that we don't need self hosted sentry yet

**Comment by arvryna** [comment]
yes. btw, planning to implement this way:

1) create a folder in root called monitoring->sentry->sentry.go (which will contain New() func) that will set the key and return sentry object is that fine ?

2) create new sentry object in tg_bot.go and receiver.go and pass it as part of constructors - NewSMTPReceiver & NewTGBot

**Comment by requiemofthesouls** [comment]
@arvryna the first one is better I think

**Comment by requiemofthesouls** [comment]
@arvryna alright

**Comment by requiemofthesouls** [comment]
actual behaviour 
![image](https://user-images.githubusercontent.com/32811996/151924665-7097eb54-811d-40e2-a64c-6c75f93a99ff.png)
