### ISSUE TITLE
Implement create email validation

### ISSUE THREAD

**Issue by requiemofthesouls** [requiemofthesouls/pigeomail#4]
implement validateMailboxName function and call it in top of handleCreateCommandStep2

**Comment by arvyshka** [comment]
Привет ) я готов сделать ) could you please assign me to this issue ?

**Comment by requiemofthesouls** [comment]
@arvyshka Привет, назначил)

**Comment by arvryna** [comment]
@requiemofthesouls : I sent you a mail regarding few questions in your email <dimamid99+work@gmail.com> . Did you get it ?

**Comment by requiemofthesouls** [comment]
> @requiemofthesouls : I sent you a mail regarding few questions in your email <dimamid99+work@gmail.com> . Did you get it ?

Hi, it was in spam 🥲.
Alright, I'll add more info how to implement this issue in description and docs how to up this project locally.
