### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by requiemofthesouls** [requiemofthesouls/pigeomail#6]
https://habr.com/ru/post/586632/
https://habr.com/ru/post/595627/

**Comment by arvryna** [comment]
how is deployment happening now ? manual or automatic ? i can see that already new commits in master are live in prod

**Comment by requiemofthesouls** [comment]
> how is deployment happening now ? manual or automatic ? i can see that already new commits in master are live in prod
manual deploy, but I'm working on it
